package com.SmartCanteen.AdminView;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JFrame;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

public class AdminMainFrm extends javax.swing.JFrame {

	/** Creates new form AdminFrm */
	public AdminMainFrm() {
		initComponents();
		//设置最大化
		this.setExtendedState(JFrame.MAXIMIZED_BOTH);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		table = new javax.swing.JDesktopPane();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu3 = new javax.swing.JMenu();
		jmiDealOrder = new javax.swing.JMenuItem();
		jMenu4 = new javax.swing.JMenu();
		jmiExit = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("\u70b9\u9910\u7cfb\u7edf\u7ba1\u7406\u4e3b\u754c\u9762");

		jMenu3.setIcon(null); // NOI18N
		jMenu3.setText("\u8ba2\u5355\u7ba1\u7406");

		jmiDealOrder.setIcon(null); // NOI18N
		jmiDealOrder.setText("\u8ba2\u5355\u5904\u7406");
		jmiDealOrder.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jmiDealOrderActionPerformed(evt);
			}
		});
		jMenu3.add(jmiDealOrder);

		jMenuBar1.add(jMenu3);
		
		mntmNewMenuItem_1 = new JMenuItem("\u5386\u53F2\u8BA2\u5355");
		mntmNewMenuItem_1.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				historicalOrder(e);
			}
		});
		jMenu3.add(mntmNewMenuItem_1);

		jMenu4.setIcon(null); // NOI18N
		jMenu4.setText("\u5176\u4ed6");

		jmiExit.setIcon(null); // NOI18N
		jmiExit.setText("\u9000\u51fa\u7cfb\u7edf");
		jmiExit.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jmiExitActionPerformed(evt);
			}
		});
		
		JMenuItem mntmNewMenuItem = new JMenuItem("\u67E5\u8BE2\u5206\u6790");
		mntmNewMenuItem.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				dataAnalyse(e);
			}
		});
		jMenu4.add(mntmNewMenuItem);
		jMenu4.add(jmiExit);

		jMenuBar1.add(jMenu4);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(table,
				javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(table,
				javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	protected void historicalOrder(ActionEvent e) {
		HistoricalOrderInterFrm historicalOrderInterFrm = new HistoricalOrderInterFrm();
		historicalOrderInterFrm.setVisible(true);
		this.table.add(historicalOrderInterFrm);
	}

	protected void dataAnalyse(ActionEvent e) {
		DataAnalyseInterFrm dataAnalyseInterFrm = new DataAnalyseInterFrm();
		dataAnalyseInterFrm.setVisible(true);
		this.table.add(dataAnalyseInterFrm);
	}

	//订单处理操作
	private void jmiDealOrderActionPerformed(java.awt.event.ActionEvent evt) {
		DealOrderInterFrm dealOrderInterFrm = new DealOrderInterFrm();
		dealOrderInterFrm.setVisible(true);
		this.table.add(dealOrderInterFrm);
	}
	

	//退出系统
	private void jmiExitActionPerformed(java.awt.event.ActionEvent evt) {
		int result = JOptionPane.showConfirmDialog(null, "是否退出点餐系统？");
		//System.out.println(result);
		if (result == 0)
			this.dispose();

	}


	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new AdminMainFrm().setVisible(true);
			}
		});
	}
	private javax.swing.JMenu jMenu3;
	private javax.swing.JMenu jMenu4;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem jmiDealOrder;
	private javax.swing.JMenuItem jmiExit;
	private javax.swing.JDesktopPane table;
	private JMenuItem mntmNewMenuItem_1;
}