package com.SmartCanteen.CustomerView;

import java.sql.Connection;

import javax.swing.JOptionPane;

import com.SmartCanteen.dao.UserDao;
import com.SmartCanteen.model.User;
import com.SmartCanteen.util.DbUtil;
import com.SmartCanteen.util.StringUtil;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JTextField;
import javax.swing.JButton;
import javax.swing.JLabel;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;


public class InfoInterFrm extends javax.swing.JInternalFrame {
	DbUtil dbUtil = new DbUtil();
	UserDao userDao = new UserDao();

	/** Creates new form AccountModify */
	public InfoInterFrm() {
		initComponents();
		this.setLocation(320, 100);
		this.userNameTxt.setText(LogOnFrm.s_currentUser.getName());
		double Account=LogOnFrm.s_currentUser.getAccount();
		this.AccountTxt.setText(Account+"");
		this.IdTxt.setText(LogOnFrm.s_currentUser.getId());
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		userNameTxt = new javax.swing.JTextField();

		setClosable(true);
		setIconifiable(true);
		setTitle("\u4E2A\u4EBA\u4FE1\u606F");

		jLabel1.setIcon(null); // NOI18N
		jLabel1.setText("\u7528\u6237\u540d\uff1a");

		jLabel2.setIcon(null); // NOI18N
		jLabel2.setText("\u8D26\u6237\u4F59\u989D\uFF1A");

		userNameTxt.setEnabled(false);
		
		AccountTxt = new JTextField();
		AccountTxt.setText((String) null);
		AccountTxt.setEnabled(false);
		
		addAccountTxt = new JTextField();
		addAccountTxt.setColumns(10);
		
		JButton btnNewButton = new JButton("\u5145\u503C");
		btnNewButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				addAccount(e);
			}
		});
		
		JLabel lblid = new JLabel();
		lblid.setText("\u8D26\u53F7\uFF1A");
		
		IdTxt = new JTextField();
		IdTxt.setText((String) null);
		IdTxt.setEnabled(false);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
						.addGroup(Alignment.LEADING, layout.createSequentialGroup()
							.addGap(126)
							.addComponent(lblid, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addGroup(Alignment.LEADING, layout.createSequentialGroup()
							.addGap(75)
							.addComponent(addAccountTxt, GroupLayout.PREFERRED_SIZE, 103, GroupLayout.PREFERRED_SIZE))
						.addGroup(Alignment.LEADING, layout.createSequentialGroup()
							.addGap(101)
							.addGroup(layout.createParallelGroup(Alignment.TRAILING)
								.addComponent(jLabel1)
								.addComponent(jLabel2))))
					.addGroup(layout.createParallelGroup(Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
							.addGap(48)
							.addComponent(btnNewButton, GroupLayout.PREFERRED_SIZE, 107, GroupLayout.PREFERRED_SIZE))
						.addGroup(layout.createSequentialGroup()
							.addGap(18)
							.addGroup(layout.createParallelGroup(Alignment.LEADING)
								.addComponent(AccountTxt, GroupLayout.PREFERRED_SIZE, 127, GroupLayout.PREFERRED_SIZE)
								.addComponent(userNameTxt, GroupLayout.PREFERRED_SIZE, 127, GroupLayout.PREFERRED_SIZE)
								.addComponent(IdTxt, GroupLayout.PREFERRED_SIZE, 127, GroupLayout.PREFERRED_SIZE))))
					.addContainerGap(55, Short.MAX_VALUE))
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(layout.createSequentialGroup()
					.addGap(41)
					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jLabel1)
						.addComponent(userNameTxt, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
					.addGap(18)
					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(lblid)
						.addComponent(IdTxt, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
					.addGap(18)
					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jLabel2)
						.addComponent(AccountTxt, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
					.addGap(18)
					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(addAccountTxt, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE)
						.addComponent(btnNewButton, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE))
					.addGap(114))
		);
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>

	protected void addAccount(ActionEvent evt) {
		Connection con = null;
		try {
			con = dbUtil.getConnection();
			double addAccount = Double.parseDouble(this.addAccountTxt.getText());
			if(userDao.Charge(con, LogOnFrm.s_currentUser, addAccount)==1) {
				JOptionPane.showMessageDialog(null, "充值成功！");
				double Account=LogOnFrm.s_currentUser.getAccount();
				LogOnFrm.s_currentUser.setAccount(Account+addAccount);
				this.AccountTxt.setText(LogOnFrm.s_currentUser.getAccount()+"");
				this.addAccountTxt.setText("");
			}
			else {
				JOptionPane.showMessageDialog(null, "充值失败！");
			}
		} catch (Exception e) {
			// TODO 自动生成的 catch 块
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, "充值失败！");
		}finally {
			try {
				dbUtil.closeConnection(con);
			} catch (Exception e) {
				// TODO 自动生成的 catch 块
				e.printStackTrace();
			}
		}
		
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JTextField userNameTxt;
	private JTextField AccountTxt;
	private JTextField addAccountTxt;
	private JTextField IdTxt;
}
